name: ecommerce_int2
description: It is about a complete ecommerce app for Android and iOS. 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"
  #sdk: ">=2.12.0 <3.0.0"  #Dye
  

dependencies:
  flutter:
    sdk: flutter
     
  mqtt_client: ^7.2.1

  #qr_code_scanner: ^0.4.0
  qr_code_scanner: ^0.3.5

  provider: ^4.3.2+2 #######################################

  #progress-state-button: "^1.0.0"
  #flutter_progress_button: '^1.0.0'
  progress_state_button: ^1.0.2

  #?????
  #rflutter_alert: ^1.0.3
  flutter_awesome_alert_box: ^1.0.1

  #qrscan: ^0.2.19  #DYE 2
  #qrscan: ^0.2.17
  
  #qr_code_scanner: ^0.4.0
  #qr_code_scanner: ^0.3.5
  
  #qr_code_scanner: ^0.4.0
  ##qr_code_scanner: ^0.0.12

  #url_launcher: ^6.0.3
  ##url_launcher: ^5.7.0
  
  #qr_code_scanner: ^0.4.0
  #url_launcher: ^6.0.3
  
  #DYE
  #path_provider: ^1.6.24
  #qr_flutter: ^3.2.0
  #barcode_scan_fix: ^1.0.2
  #DYE

  #DYE
  #cupertino_icons: ^0.1.2  
  #barcode_scan: ^1.0.0  

  #flutter_barcode_scanner: ^0.0.9 
  #flutter_barcode_scanner: ^2.0.0
  #barcode_scan: ^3.0.1
  #qr_code_scanner: ^0.4.0
  
  #DYE
    
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: 1.0.0
  cupertino_icons: 1.0.0 #DYE 2
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  rubber: 0.4.0
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: ^0.12.2
  flutter_rating_bar: 3.2.0+1
  intl: 0.16.1
  numberpicker: ^1.0.0
  flare_splash_screen: 3.0.1
  flutter_svg: 0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.8.1

  #DYE
  #qr_code_scanner: ^0.0.10
    #path: ../
  #DYE

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf

